version: "3.9"

services:
  database:
    image: postgres:15
    container_name: chatapp_db
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ChatGeniusDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatapp_web
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for development
      - .:/app
      # Prevent mounting node_modules from host
      - /app/node_modules
      - /app/.next
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data: 